<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package     Fooman_Jirafe
 * @copyright   Copyright (c) 2010 Jirafe Inc (http://www.jirafe.com)
 * @copyright   Copyright (c) 2010 Fooman Limited (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $_isConfigured = Mage::helper('foomanjirafe')->isConfigured() ?>

<?php if ($_isConfigured) :?>
    <?php $_siteId = $this->getSiteId() ?>
    <?php $_pkBaseURL = $this->getPkBaseURL() ?>
    <?php $_pkBaseURLSecure = $this->getPkBaseURLSecure() ?>

    <!-- Piwik -->
    <script type="text/javascript">
    var pkBaseURL = (("https:" == document.location.protocol) ? "<?php echo $_pkBaseURLSecure ?>" : "<?php echo $_pkBaseURL ?>");
    document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
    </script><script type="text/javascript">
    try {
    var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", <?php echo $_siteId ?>);
    <?php echo $this->getTrackingInfo() ?>
    piwikTracker.enableLinkTracking();
    <?php echo $this->getAdditionalTrackingInfo() ?>
    } catch( err ) {}
    </script><noscript><p><img src="<?php echo $_pkBaseURL ?>piwik.php?idsite=<?php echo $_siteId ?>" style="border:0" alt="" /></p></noscript>
    <!-- End Piwik Tag -->
<?php endif;?>