<?php if ($this->isJirafeDashboardActive()) : ?>
    <?php $apiBaseUrl = Fooman_Jirafe_Model_Api::JIRAFE_API_URL ?>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jquery-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jquery-ui-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jquery-jirafe.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/raphael-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-chart.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-api.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-model.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-ui.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe.js"></script>
<?php endif; ?>