<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package     Fooman_Jirafe
 * @copyright   Copyright (c) 2010 Jirafe Inc (http://www.jirafe.com)
 * @copyright   Copyright (c) 2010 Fooman Limited (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="jirafe"></div>
<script type="text/javascript">
<!--
jQuery.noConflict();
jQuery('#jirafe').Jirafe({
    api_url:    '<?php echo $this->getDashboardApiUrl()?>',
    api_token:  '<?php echo $this->getJirafeUserToken()?>',
    app_id:     <?php echo $this->getJirafeApplicationId()?>
});
-->

</script>

