<?php if ($this->isJirafeDashboardActive()) : ?>
    <?php $apiBaseUrl = Fooman_Jirafe_Model_Api::JIRAFE_API_SERVER ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $apiBaseUrl?>bundles/jirafe/css/jirafe-ui.css" media="all" />

    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jquery-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jquery-ui-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/raphael-min.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/raphaeljs-line-chart.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-api.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-model.js"></script>

    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/ui/graph-tabs.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/ui/store-selector.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/ui/funnel.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/jirafe-controller.js"></script>
    <script type="text/javascript" src="<?php echo $apiBaseUrl?>bundles/jirafe/js/action/visitor-total.js"></script>
<?php endif; ?>