<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package     Fooman_Jirafe
 * @copyright   Copyright (c) 2010 Jirafe Inc (http://www.jirafe.com)
 * @copyright   Copyright (c) 2010 Fooman Limited (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->__('Status'); ?>: <?php echo $this->getStatusMessage();?>
<?php if($this->isConfigured()):?>
<p><?php echo $this->__('Jirafe has been configured correctly.'); ?></p>
<?php else:?>
<p><?php echo $this->__('Jirafe has reported errors. Please try the Sychronise action below.'); ?>
<?php endif;?>
<p><a href="<?php echo $this->getSyncUrl()?>"><?php echo $this->__('Synchronise Magento with Jirafe'); ?></a> <br/>
    <a href="<?php echo $this->getReportUrl()?>"><?php echo $this->__('Run Report'); ?></a></p>