<?php $_helper = Mage::helper('foomanjirafe'); ?>
<?php $_isConfigured = $_helper->isConfigured() ?>
<?php if ($_isConfigured) :?>
    <?php $_pkBaseURLSecure = $_helper->getStoreConfig('pkBaseURLSecure') ?>
    <?php $_tokenAuth = $_helper->getStoreConfig('tokenAuth') ?>
    <?php /* <object style="visibility: visible;" id="VisitsSummarygetEvolutionGraphChart_swf"
            data="<?php echo $_pkBaseURLSecure ?>libs/open-flash-chart/open-flash-chart.swf?piwik=1.0"
            bgcolor="#FFFFFF"
            type="application/x-shockwave-flash"
            height="150"
            width="100%">
        <param value="always" name="allowScriptAccess">
        <param value="transparent" name="wmode">
        <param value="data-file=<?php echo urlencode($_pkBaseURLSecure)?>index.php%3Fmodule%3DVisitsSummary%26action%3DgetEvolutionGraph%26columns%5B%5D%3Dnb_visits%26idSite%3D1%26period%3Dday%26date%3D2010-09-26%2C2010-10-25%26viewDataTable%3DgenerateDataChartEvolution&token_auth=<?php echo $_tokenAuth ?>&id=VisitsSummarygetEvolutionGraphChart_swf&loading=Loading..."
               name="flashvars">
    </object> */ ?>


    <div id="widgetIframe">
        <iframe width="100%"
                height="220"
                src="<?php echo $_pkBaseURLSecure ?>index.php?module=Widgetize&action=iframe&columns[]=nb_visits&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=1&period=day&date=2010-10-24&disableLink=1&token_auth=<?php echo $_tokenAuth ?>"
                scrolling="no"
                frameborder="0"
                marginheight="0"
                marginwidth="0">

        </iframe>
    </div>


    <div id="widgetIframe2">
        <iframe width="350"
                height="500"
                src="<?php echo $_pkBaseURLSecure ?>index.php?module=Widgetize&action=iframe&moduleToWidgetize=Live&actionToWidgetize=widget&idSite=1&period=week&date=2010-10-25&disableLink=1&token_auth=<?php echo $_tokenAuth ?>"
                scrolling="no"
                frameborder="0"
                marginheight="0"
                marginwidth="0">
        </iframe>
    </div>

<?php endif; ?>