<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package     Fooman_Jirafe
 * @copyright   Copyright (c) 2010 Jirafe Inc (http://www.jirafe.com)
 * @copyright   Copyright (c) 2010 Fooman Limited (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $statusCssClass = $this->isOk()?'success-msg':'error-msg' ?>
<ul class="messages">
    <li class="<?php echo $statusCssClass?>">
<?php if($this->isConfigured()):?>
     <?php echo $this->__('Jirafe has been configured correctly.'); ?>
<?php else:?>
    <?php echo $this->__('Jirafe has reported errors. Please try the sychronise action.'); ?>
<?php endif;?>
 <?php echo $this->__('Last Status'); ?>: <?php echo $this->getStatusMessage();?>
 <?php if ($this->isDebug()): ?>
     <span style="float:right;"><a href="<?php echo $this->getSyncUrl()?>"><?php echo $this->__('Synchronise Magento with Jirafe'); ?></a> |
        <a href="<?php echo $this->getReportUrl()?>"><?php echo $this->__('Run Report'); ?></a></span></li>
 <?php endif;?>
</ul>
